In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

# 1629 Características del hogar

In [ ]:
# RECH0 es una base a nivel hogar
# RECH1 Es la base a nivel persona del hogar.
# RECH4 Está a nivel persona
# RECHM mortalidad
# Para nuestros fines nos conviene usar RECH0 y RECH1

In [ ]:
base = Path("../data/demografica_salud_ENDES")

ruta_rech0 = base / "1629" / "RECH0_2024.csv"
ruta_rech1 = base / "1629" / "RECH1_2024.csv"

rech0 = pd.read_csv(ruta_rech0, dtype=str)
rech1 = pd.read_csv(ruta_rech1, dtype=str)

In [24]:
rech0

,ID1,HHID,HV000,HV001,HV002,HV002A,HV003,HV004,HV007,HV008,...,HV043,HV044,UBIGEO,HV022,HV005,CODCCPP,NOMCCPP,LATITUDY,LONGITUDX,NCONGLOME1
0,2024,325502001,PE6,3255,20,1,0,3255,2024,1493,...,0,1,010101,2,0,0001,CHACHAPOYAS,-6.2258317,-77.8613021,07076
1,2024,325503101,PE6,3255,31,1,2,3255,2024,1493,...,0,1,010101,2,74497,0001,CHACHAPOYAS,-6.2258317,-77.8613021,07076
2,2024,325503901,PE6,3255,39,1,1,3255,2024,1493,...,0,1,010101,2,607697,0001,CHACHAPOYAS,-6.2258317,-77.8613021,07076
3,2024,325504001,PE6,3255,40,1,1,3255,2024,1493,...,0,1,010101,2,607697,0001,CHACHAPOYAS,-6.2258317,-77.8613021,07076
4,2024,325504701,PE6,3255,47,1,2,3255,2024,1493,...,0,1,010101,2,74497,0001,CHACHAPOYAS,-6.2258317,-77.8613021,07076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37385,2024,705704301,PE6,7057,43,1,1,7057,2024,1500,...,0,1,110101,100,251377,0001,ICA,-14.03525917,-75.737065,3426301
37386,2024,705705001,PE6,7057,50,1,2,7057,2024,1500,...,0,1,110101,100,251377,0001,ICA,-14.03525917,-75.737065,3426301
37387,2024,705706501,PE6,7057,65,1,2,7057,2024,1500,...,0,1,110101,100,251377,0001,ICA,-14.03525917,-75.737065,3426301
37388,2024,705707301,PE6,7057,73,1,0,7057,2024,1500,...,0,1,110101,100,0,0001,ICA,-14.03525917,-75.737065,3426301
37389,2024,705708801,PE6,7057,88,1,1,7057,2024,1500,...,0,1,110101,100,251377,0001,ICA,-14.03525917,-75.737065,3426301

In [ ]:
rech0.head()
rech1.head()
rech0.columns.tolist()
rech1.columns.tolist()

# 1630

In [16]:
ruta_rech23 = base / "1630" / "RECH23_2024.csv"

rech23 = pd.read_csv(ruta_rech23, dtype=str)

In [17]:
rech23

,ID1,HHID,HV201,HV202,HV204,HV205,HV206,HV207,HV208,HV209,...,SH78,SH79,SH224,SH225U,SH225,SH227,QH227A,QH227B,HV270,HV271
0,2024,325502001,,,,,,,,,...,,,,,,,,,,
1,2024,325503101,11,,996,22,1,0,0,0,...,0,,9,,,2,1,1,2,-.224175006493913
2,2024,325503901,11,,996,11,1,0,0,0,...,0,,9,,,3,1,1,3,.366367930920724
3,2024,325504001,11,,996,22,1,1,0,0,...,0,,9,,,3,1,1,1,-.76953388723092
4,2024,325504701,71,11,996,11,1,1,1,1,...,0,,9,,,5,,,2,.0566849954924239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37385,2024,705704301,71,61,1,21,1,1,1,1,...,0,,9,,,5,,,2,.212642980267205
37386,2024,705705001,96,96,1,21,1,1,1,0,...,0,,9,,,3,1,1,2,-.519781023549353
37387,2024,705706501,71,96,30,23,1,0,1,0,...,0,,9,,,5,,,2,-.430807838924267
37388,2024,705707301,,,,,,,,,...,,,,,,,,,,
37389,2024,705708801,11,,996,11,1,1,1,1,...,0,,9,,,3,1,1,4,.888905718799299

# 1638 - Peso talla y anemia

In [ ]:
# RECH 6 es la base de niñas y niños en el hogar 
# RECH 5 esla base de mujeres de 12 a 49 años
# RECH 44 Es una base de niñas y niños en el cuestionario individual (no usaremos esta)

In [18]:
ruta_rech6 = base / "1638" / "RECH6_2024.csv"
ruta_rech5 = base / "1638" / "RECH5_2024.csv"

rech6 = pd.read_csv(ruta_rech6, dtype=str)
rech5 = pd.read_csv(ruta_rech5, dtype=str)

In [19]:
rech5

,ID1,HHID,HA0,HA1,HA2,HA3,HA4,HA5,HA6,HA11,...,HA60,HA61,HA62,HA63,HA64,HA65,HA66,HA67,HA68,HA69
0,2024,325503101,2,38,704,1525,301,-188,9315,108,...,,,,,,1,2,5,2,
1,2024,325503101,4,15,541,1518,591,-156,9355,16,...,,,,,,1,2,3,2,
2,2024,325503901,2,17,498,1602,2931,-54,9798,-101,...,,,,,,1,2,5,2,
3,2024,325504701,2,32,653,1443,6,-325,8814,146,...,,,,,,1,2,5,2,
4,2024,325505001,1,36,689,1486,57,-253,9077,122,...,,,,,,1,1,6,1,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38483,2024,705705001,6,30,707,1635,4861,-3,9987,60,...,,,,,,1,2,3,2,
38484,2024,705705001,7,12,494,1575,6430,37,10159,-143,...,,,,,,1,1,6,1,
38485,2024,705706501,2,35,584,1489,65,-248,9095,7,...,,,,,,1,2,5,2,
38486,2024,705708801,1,39,652,1422,2,-361,8686,134,...,,,,,,1,2,3,2,
38487,2024,705708801,3,13,372,1456,183,-209,9127,-277,...,,,,,,1,1,6,1,

# 1640

In [23]:
# CSALUD01_2024: Es la base del cuestionario de salud para personas de 15 años a más.
# CSALUD08_2024: Es la base de salud bucal, ocular y mental en niñas y niños de 0 a 11 años.
# USAREMOS AMBOS

In [21]:
ruta_SALUD1 = base / "1640" / "CSALUD01_2024.csv"
ruta_SALUD8 = base / "1640" / "CSALUD08_2024.csv"

SALUD1 = pd.read_csv(ruta_SALUD1, dtype=str)
SALUD8 = pd.read_csv(ruta_SALUD8, dtype=str)

In [22]:
SALUD1

,ID1,HHID,QHCLUSTER,QHNUMBER,QHHOME,QSNUMERO,QSINTM,QSINTY,QSTOTVISIT,QSRESULT,...,QS731_E,QS731_EA,QS731_F,QS731_G,QS731_H,QS731_I,QS731_J,QS731_X,QS731_Y,PESO15_AMAS
0,2024,325503101,3255,31,1,2,5,2024,1,1,...,,,,,,,,,,157182.172077703
1,2024,325503901,3255,39,1,2,5,2024,1,1,...,,,,,,,,,,200845.215117424
2,2024,325504001,3255,40,1,1,5,2024,1,1,...,,,,,,,,,,432165.467953967
3,2024,325504701,3255,47,1,1,5,2024,1,1,...,,,,,,,,,,162338.353517329
4,2024,325505001,3255,50,1,2,5,2024,2,1,...,,,,,,,,,,162338.353517329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34013,2024,705703901,7057,39,1,1,12,2024,1,1,...,,,,,,,,,,413006.910789338
34014,2024,705704301,7057,43,1,2,12,2024,3,1,...,,,,,,,,,,885502.426143606
34015,2024,705705001,7057,50,1,2,12,2024,5,1,...,,,,,,,,,,379954.605473915
34016,2024,705706501,7057,65,1,2,12,2024,1,1,...,,,,,,,,,,413006.910789338
34017,2024,705708801,7057,88,1,1,12,2024,1,1,...,,,,,,,,,,413006.910789338